# Generated by Django 4.2.4 on 2023-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_purchase',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchasing_status',
            field=models.BooleanField(default=False),
        ),
    ]
